name: CI - Smoke Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: ['3.11']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi

      - name: Run smoke test (PowerShell on Windows / Shell on Linux)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          Write-Host "Running smoke test script"
          pwsh -File "scripts/smoke_test.ps1"

      - name: Run pytest
        shell: bash
        run: |
          echo "Running pytest"
          python -m pip install pytest
          python -m pytest -q
